# 创建一个secret,名字为super-secret包含用户名bob,创建pod1挂载该secret，路径为/secret，
# 创建pod2，使用环境变量引用该secret，该变量的环境变量名为ABC
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: mypod
      image: redis
      volumeMounts:
        - name: foo
          mountPath: "/secret"
          readOnly: true
  volumes:
    - name: foo
      secret:
        secretName: super-secret
