version: '2'
services:
  webserver:
    # image: phpstorm/php-56-apache-xdebug-25
    build: ./docker-build/webserver
    ports:
      - "6080:80"
    volumes:
      - ./www:/www
      - ./docker-build/logs:/var/log/apache2
    environment:
      #change the line below with your IP address
      XDEBUG_CONFIG: remote_host=host.docker.internal
  mysql:
    build: ./docker-build/mysql
    ports:
      - "33064:3306"
    volumes:
      - ./docker-build/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_PASSPORD-123456}