# 一个pod多个容器
apiVersion: v1
kind: Pod
metadata:
  name: kucc
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.17.1
    # IfNotPresent | Always | Never
    imagePullPolicy: IfNotPresent # 拉取策略 kubectl explain pods.spec.containers.imagePullPolicy
    ports:
    - containerPort: 80 # 对service暴露端口
  - name: redis
    image: redis
  - name: memcached
    image: memcached
