# https://docs.docker.com/compose/compose-file/
version: "3"
services:
  nginx:
      build: ./docker-build/nginx
      ports:
        - "${DOCKER_WEB_PORT-8006}:80"
      links:
        - "php"
      volumes:
        - ./docker-build/log/nginx:/var/log/nginx
        - .:/www

  php:
      build:
        context: ./docker-build/php
        args:
          - INSTALL_COMPOSER=${PHP_INSTALL_COMPOSER}
          - INSTALL_MONGO=${PHP_INSTALL_MONGO}
          - INSTALL_REDIS=${PHP_INSTALL_REDIS}
          - INSTALL_XDEBUG=${PHP_INSTALL_XDEBUG}
      ports:
        - "9001:9000"
      links:
        - "mysql"
      volumes:
        - .:/www

  mysql:
      image: 'mysql:5.6'
      ports:
        - "${DOCKER_MYSQL_PORT-33060}:3306"
      volumes:
        - ./docker-build/mysql/data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_PASSWORD-123456}
